Remove versioneer
Electrostatics/pdb2pqr pull request #212
Opened 2021-07-13 14:55 UTC by intendo

This will remove the confusion of versioneer. The changes are based on what we did for mmcif_pdbx and may make the most recent request for releasing on conda possible (although I don't know how to do that).

2021-07-13 15:55 UTC, intendo commented
@sobolevnrm can we remove the pdb2pka file?

2021-07-14 02:18 UTC, sobolevnrm requested changes

2021-07-14 02:18 UTC, sobolevnrm commented on setup.cfg
> +source = mmcif_pdbx
I don't understand this -- why is `source = mmcif_pdbx` ?

2021-07-14 12:09 UTC, sobolevnrm approved these changes

2021-07-14 12:09 UTC, merged