Allow using hexadecimal ATOM id
Electrostatics/pdb2pqr pull request #370
Opened 2023-09-06 11:48 UTC by SSchott

Was facing issues parsing too big PDBs. I adapted the parsing for the serial entry for ATOM to allow hexadecimal notation, as when PDBs are rewritten by VMD. I don't know how much it would be necessary to include this for other atom id dependent entries. If so, making a function for it might be necessary. Anything that goes against such a move?

2023-09-09 18:07 UTC, sobolevnrm commented
Can you please provide more information, including links to references, about PDB files using hexademical numbering?  I'm unfamiliar with this.  Thank you!

2023-09-10 09:45 UTC, SSchott commented
I didn't find "official" documentation, aside the mailing list [here](https://www.ks.uiuc.edu/Research/vmd/mailing_list/vmd-l/20274.html) , but is already used by other packages, e.g. [here](https://search.r-project.org/CRAN/refmans/bio3d/html/read.pdb.html) . Seems like adding it for resnumbers is also an option.

2023-10-08 18:56 UTC, sobolevnrm requested changes
Hello --

I'm hesitant to add this functionality to PDB2PQR because it is a non-standard format.  However, if we do add it, can you please add some tests to make sure it doesn't break other functionality, particularly when parsing PDB entries with chain IDs or insertion codes?

In general, all new functionality in PDB2PQR should include tests to demonstrate when the code works, when it breaks, and how it integrates with other features in the code.

Thank you,

Nathan

2023-10-16 12:01 UTC, GerardCarreraCardona commented
Probably a quick fix using this:
[Portable hy36encode() and hy36decode() implementations](https://github.com/cctbx/cctbx_project/blob/master/iotbx/pdb/hybrid_36.py) or even a function from PROPKA
`propka.hybrid36.decode(input_string)`

When VMD or pymol have to write large PDB files they use [Hybrid-36 format ](https://propka.readthedocs.io/en/latest/api/propka.hybrid36.html)

(TLDR: PDB file that uses Hexadecimal integers as ID when ID exceeds 99999)

When PDB2PQR encounters this it returns this error:
`ValueError: invalid literal for int() with base 10: '186a0'` 186a0 is 100000 in decimal so its definitely a problem when it reaches values over 99999 and finds a hexadecimal integer.

My guess is that it can be solved either by changing the main code to parse HEX values or by changing the input file from Hybrid_36 to a normal PDB.

2023-10-16 12:02 UTC, GerardCarreraCardona approved these changes

2023-10-28 07:38 UTC, speleo3 commented
VMD's solution will produce many "hex" numbers which are digit-only, and thus will not be parsed back correctly and will produce non-unique atom IDs. So I wonder how useful this really is, and if it is any better than to just write zeros or 99999 for overflowing numbers.

```py
>>> int("%05x" % 100096)
18700
```

2023-10-30 15:46 UTC, SSchott commented
Hi,
Thanks for the comments. @sobolevnrm I'll see what I can do regarding a test. In any case, any standard PDB should never trigger the except section, as ATOM IDs should always be int, but we know how the PDB-space looks like.... @speleo3 I don't follow what you mean. The try and except should ensure only hex numbers are transformed into a decimal number. It should ensure traceability in the long term.

2024-01-03 14:56 UTC, SSchott commented
Finally got around this. I made a draft in #383 . Let me know if it goes in line with what you were looking for.

2024-01-03 14:56 UTC, closed without merging