Adding pKa-ANI to titration state prediction for pdb2pqr
Electrostatics/pdb2pqr pull request #407
Opened 2024-11-20 17:26 UTC by sastrys1

2024-11-21 03:49 UTC, sobolevnrm requested changes
I got partway through the review and had several questions/requests that will affect the rest of the review, so I stopped there.

2024-11-21 03:49 UTC, sobolevnrm commented on pdb2pqr/dat/ASP_ani2x_FINAL_MODEL_F100.joblib
Can you please add a README.md to the `dat/` directory that describes these files?  Is there any good way to check whether `*.joblib` files are malicious?

2024-11-21 03:49 UTC, sobolevnrm commented on tests/pkaani_tests/test_pHs_pkaani.sh
Please use the pytest framework for tests to integrate with the rest of the test suite for PDB2PQR.

2024-11-21 03:49 UTC, sobolevnrm commented on pdb2pqr/pkaani/ani_descriptors.py
This is a lot of code.  Does the original repo have a Python package we could import instead?  I would prefer to import an external module with its own set of tests and then focus on integration tests for this new functionality.

2024-11-21 03:49 UTC, sobolevnrm commented on setup.py
> +#	if available to the packaging tools before installation.
I'm not sure what changed here.  Did you add tabs?  If so, please preserve the original spacing format here and elsewhere.

2024-11-21 03:50 UTC, sobolevnrm commented
Please note the failing tests for this PR.

2024-11-21 17:56 UTC, sastrys1 commented on pdb2pqr/pkaani/ani_descriptors.py
Yeah, that's a good idea. I'm working on packaging it into a module that can be imported by others - I agree this isn't ideal.

2024-11-21 17:58 UTC, sastrys1 commented on pdb2pqr/dat/ASP_ani2x_FINAL_MODEL_F100.joblib
I think it'll be better to just do away with these if I can just make the pKa-ANI repo into an importable package

2025-02-14 01:00 UTC, sastrys1 commented
@sobolevnrm Wanted to circle back on this - I have uploaded the pKa-ANI package as a standalone importable package in PyPI. Now, to get access to the functions all you need to do is `pip install pkaani` and then `import pkaani` in a python script. 

It now installs the dependencies through PyPI, the only one that it can't do is `ambertools` (users must install `ambertools` through conda). Now, the code demand becomes a lot smaller and the only additional piece is having PDB2PQR users install ambertools via conda if they want to use pKa-ANI. What do you think about this?

2025-02-14 02:57 UTC, sastrys1 commented
Is there a reason that pdb2pqr needs Python >= 3.11? The pKa-ANI package I am trying to connect is dependent on sklearn 1.0.2, but it seems like sklearn 1.0.2 is not compatible with Python 3.11

2025-02-14 04:38 UTC, sobolevnrm commented
Yes, I'd like to keep the package current with the latest version of Python.

2025-02-14 08:21 UTC, kiyoon commented
@sastrys1 you can either relieve the version requirement of the ANI package to use wider versions of sklearn (ask the maintainer) or use 3.6.x version of pdb2pqr.

@sobolevnrm I think Python 3.10 would actually run without a problem. We can also consider widening the supported version a little because a lot of other projects still use python 3.10.

2025-02-14 08:54 UTC, sastrys1 commented
I see, it looks like the models in the pKa-ANI package are preserved as "joblib" files and can only be read by `sklearn version 1.0.2`, which is incompatible with Python 3.11. Do you happen to know how to take old joblib files and save them into forwards-compatible formats? I have reached out to the maintainer of that repo, hopefully they can fix it

2025-02-14 09:43 UTC, sastrys1 commented
@kiyoon Just tested on the pdb2pqr 3.6.2 version - this works really smoothly with pKa-ANI in Python 3.8. However at python 3.10 the dependency gnarliness between sklearn 1.0.2, python 3.10, and numpy makes everything break down. I think the easiest way forward is to have them upgrade the models unless you all are interested in merging in my mod of pdb2pqr 3.6.1 which works with Python 3.8

2025-02-14 14:04 UTC, sobolevnrm commented
> @sastrys1 you can either relieve the version requirement of the ANI package to use wider versions of sklearn (ask the maintainer) or use 3.6.x version of pdb2pqr.
> 
> @sobolevnrm I think Python 3.10 would actually run without a problem. We can also consider widening the supported version a little because a lot of other projects still use python 3.10.

@kiyoon I'm happy to accept >=3.10 if you believe it won't break anything.  Could one of you please create a separate PR with this change?

2025-02-14 20:15 UTC, sastrys1 commented
@sobolevnrm Unfortunately even with Python 3.10 its still not compatible with sklearn 1.0.2, regardless of changing to >=3.10 it still would not be compatible with the pKa-ANI package as it stands (the pKa-ANI maintainers recommend python 3.8 as a matter of fact). Hopefully the maintainers are open to making the package more long-term sustainable with newer versions of python

2025-02-15 07:06 UTC, kiyoon commented
@sastrys1 Python 3.8 is out of support now and we can't support that version. If they don't support it you can manually build from source and fiddle with the requirements yourself.

2025-02-17 02:00 UTC, seankhl commented
@sastrys1 Correct me if I'm wrong, but I believe that ambertools is only used for the `prep_pdb` function inside pKa-ANI, which actually isn't used in this PR. I believe your PR should function without ambertools installed. Many of the "preparation" steps happen within pdb2pqr, such as adding missing heavy atoms and default hydrogen states to the amino acids, so this functionality isn't required for use in pdb2pqr as I understand it. (Though, perhaps some slight differences in how these are done may lead to unexpected outcomes when these programs are combined in this way.)

I think in an ideal world this non-python dependency would be handled explicitly.
  - The upstream pacakge could check for the existence of the called ambertools executables at runtime and only use `prep_pdb` if it can be found, otherwise just confirming the correctness of the input PDBs: it would then continue if the PDBs are already in the appropraite state and exit with an error otherwise.
  - To go further, the upstream package could check for `ambertools` at install time and fail to install if it is not found (similar to how other python packages with non-python dependencies work). In this case, perhaps the `prep_pdb` functionality could be placed behind a feature flag to allow for installation and use of `calculate_pka` without the need for ambertools.

I greatly appreciate your efforts to get pKa-ANI into pdb2pqr in the first place, so don't take this as a request. As someone interested in this I'm just outlining my thoughts on how some of the challenges in terms of making pKa-ANI usable from within pdb2pqr.

2025-02-17 02:31 UTC, seankhl commented
On the sklearn dependency, though it does appear that everything might just perfectly work out at python 3.9 (sklearn 1.0.2 is compatible with python 3.9, which is not yet EOL). Though I do generally agree that the pKa-ANI folks will eventually need to update their model files if they intend for their work to be used by other projects going forward.

2025-02-17 03:35 UTC, kiyoon commented
Python 3.9 will reach its end of life in 7 months. I don't see the point in supporting the version just for this specific issue when you can just downgrade pdb2pqr to an older version. But for Python 3.10 I think it's good to add the support.

2025-02-17 05:08 UTC, sobolevnrm commented
Yes, I agree with @kiyoon -- 3.10 is worth supporting, but going older than that doesn't make sense to me.

2025-02-17 14:45 UTC, seankhl commented
Just to be clear I didn't intend to suggest opening up to python 3.9 and completely agree with that evaluation. It seems from https://github.com/isayevlab/pKa-ANI/issues/11 that they are interested in resolving this!

2025-02-17 19:32 UTC, sastrys1 commented
Woww, so happy to see so much discussion on this!! Thank you all for the support. @seankhl is correct, honestly `ambertools` is only used in the `prep_pdb.py` section which we don't really need. The way this code is written right now, the `prep_pdb()` would never get used.

Wym by non python dependency? Ambertools is a conda python package?  

> I greatly appreciate your efforts to get pKa-ANI into pdb2pqr in the first place, so don't take this as a request

Warms my heart to hear this!

On the accessibility in Python 3.10, I had another idea - a web server? I built this old version in Python 3.9, deployed it in Heroku and then the pKa-ANI results just get pinged from there.

2025-02-17 20:17 UTC, sastrys1 commented
I just pushed a working version of a connection of pdb2pqr and pKa-ANI that uses a web server for a small test PDB and is able to calculate the pKas using pKa-ANI. The next step now is to deploy it in a place that doesn't have crazy low memory limits or whatever. @sobolevnrm Could you possibly deploy using the same stack that the APBS server uses?

2025-02-17 21:48 UTC, sastrys1 commented
Decided to make a new PR (#427), branched off from the newest branch. The proof of concept is there for the web server idea, but the implementation and deployment details should be discussed.

2025-02-17 21:48 UTC, closed without merging

2025-03-05 03:34 UTC, sobolevnrm commented
Sounds great!